[project]
name = "betting"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "izarte", email = "inigozarate01@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "click>=8.2.1",
    "gymnasium>=0.29.1,<1.2.0",
    "numpy>=2.3.1",
    "pandas>=2.3.1",
    "rich>=14.0.0",
    "stable-baselines3>=2.6.0",
    "tensorboard>=2.20.0",
    "tqdm>=4.67.1",
]

[project.scripts]
betting = "betting.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
